export const textCards = [
  { id: 1, city: "Lagos", hotels: "3,455" },
  { id: 2, city: "Abuja", hotels: "1,170" },
  { id: 3, city: "Port Harcourt", hotels: "396" },
  { id: 4, city: "Kaduna", hotels: "332" },
  { id: 5, city: "Uyo", hotels: "204" },
  { id: 6, city: "Ibadan", hotels: "450" },
];

export const hotels = [
  {
    id: 1,
    name: "Wavecrest Beach Res...",
    address: "Ibeju-Lekki, Lagos",
    image: "/wavecrest-beach-resort-1470633-12.jpg",
  },
  {
    id: 2,
    name: "The Avenue Suites",
    address: "Victoria-island, Lagos",
    image: "/the-avenue-suites-92856-11.jpg",
  },
  {
    id: 3,
    name: "Appleville Suites Ikeja",
    address: "Ikeja, Lagos",
    image: "/appleville-suites-1441443-5.jpg",
  },
  {
    id: 4,
    name: "Begonia Hotel Oyo",
    address: "Ilora, Oyo",
    image: "/begonia-hotel-1004331-35.jpg",
  },
  {
    id: 5,
    name: "Bon Hotel Garden City...",
    address: "Port-harcourt, Rivers",
    image: "/bon-hotel-garden-city-port-harcourt-1470786-11.jpg",
  },
  {
    id: 6,
    name: "Luxol Homes Suites",
    address: "Ikeja, Lagos",
    image: "/luxol-homes--suites-1470842-13.jpg",
  },
];

export const cities = [
  {
    image: "/lagos_city1.jpg",
    number: "3,456",
    city: "Lagos",
  },
  {
    image: "/abuja_city1.jpg",
    number: "1,171",
    city: "Abuja",
  },
  {
    image: "/crossriver_city1.jpg",
    number: "272",
    city: "Calabar",
  },
  {
    image: "/port-harcourt_city1.jpg",
    number: "396",
    city: "Port Harcourt",
  },
  {
    image: "/owerri_city1.jpg",
    number: "195",
    city: "Owerri",
  },
  {
    image: "/uyo_city1.jpg",
    number: "204",
    city: "Uyo",
  },
];

export const endpoints = [
  { hotels: "296", state: "Abia", reviews: "173" },
  { hotels: "1,171", state: "Abuja", reviews: "2,470" },
  { hotels: "70", state: "Adamawa", reviews: "48" },
  { hotels: "477", state: "Akwa Ibom", reviews: "304" },
  { hotels: "299", state: "Anambra", reviews: "139" },
  { hotels: "52", state: "Bauchi", reviews: "59" },
  { hotels: "179", state: "Bayelsa", reviews: "58" },
  { hotels: "294", state: "Benue", reviews: "41" },
  { hotels: "25", state: "Borno", reviews: "12" },
  { hotels: "360", state: "Cross River", reviews: "345" },
  { hotels: "647", state: "Delta", reviews: "464" },
  { hotels: "101", state: "Ebonyi", reviews: "26" },
  { hotels: "377", state: "Edo", reviews: "505" },
  { hotels: "231", state: "Ekiti", reviews: "208" },
  { hotels: "358", state: "Enugu", reviews: "461" },
  { hotels: "1", state: "FCT", reviews: "no" },
  { hotels: "44", state: "Gombe", reviews: "24" },
  { hotels: "339", state: "Imo", reviews: "323" },
  { hotels: "33", state: "Jigawa", reviews: "5" },
  { hotels: "332", state: "Kaduna", reviews: "266" },
  { hotels: "126", state: "Kano", reviews: "130" },
  { hotels: "32", state: "Katsina", reviews: "24" },
  { hotels: "27", state: "Kebbi", reviews: "10" },
  { hotels: "264", state: "Kogi", reviews: "53" },
  { hotels: "334", state: "Kwara", reviews: "314" },
  { hotels: "3456", state: "Lagos", reviews: "8832" },
  { hotels: "237", state: "Nasarawa", reviews: "63" },
  { hotels: "111", state: "Niger", reviews: "59" },
  { hotels: "747", state: "Ogun", reviews: "532" },
  { hotels: "258", state: "Ondo", reviews: "204" },
  { hotels: "326", state: "Osun", reviews: "273" },
  { hotels: "656", state: "Oyo", reviews: "701" },
  { hotels: "286", state: "Plateau", reviews: "144" },
  { hotels: "533", state: "Rivers", reviews: "608" },
  { hotels: "21", state: "Sokoto", reviews: "52" },
  { hotels: "97", state: "Taraba", reviews: "6" },
  { hotels: "11", state: "Yobe", reviews: "no" },
  { hotels: "28", state: "Zamfara", reviews: "10" },
];
